// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://demtljoqscokqmzouuvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbXRsam9xc2Nva3Ftem91dXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDg4NjUsImV4cCI6MjA2NDYyNDg2NX0.0xj3-euKt7mSdybt0V2Hg3657L8UhX3oOSokSsH2pSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);